# Generated by Django 3.0.4 on 2020-04-04 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='isactive',
            field=models.BooleanField(default=True),
        ),
    ]
