# Generated by Django 3.0.4 on 2020-05-19 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce_site', '0007_auto_20200518_0733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='mail',
            field=models.EmailField(max_length=30),
        ),
    ]
