# Generated by Django 3.0.4 on 2020-05-28 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce_site', '0018_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='credit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
